name: Step 5, Merge your pull request

# This step triggers after a pull requst is merged to `main`
# This step sets STEP to X
# This step closes <details id=5> and opens <details id=X>

# This will run every time we create push a commit to `main`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_merge:
    name: On merge

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    env:
      NEW_BRANCH: step-x

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Create step-x branch
        runs: |
          echo "Make a branch"
          git checkout -b $NEW_BRANCH

          echo "Push"
          git push --set-upstream origin $NEW_BRANCH

      # TODO: figure out a better way to deal with the lock on `main`
      # Update README to close <details id=5> and open <details id=X>
      # and set STEP to 'X'
      - name: Update to step X
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: X
          base_branch_name: $NEW_BRANCH
          branch_name: ci

      - name: Create a pull request
        runs: |
          echo "Make a pull request"
          # Reference https://cli.github.com/manual/gh_pr_create
          gh pr create --title "Update to step X" --body "Update to step X"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
